{{- if .Values.global.render -}}
---
apiVersion: batch/v1
kind: Job
metadata:
  name: config-oauth-keycloak
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "3"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
{{- if $.Values.global.argocd.enabled }}
    argocd.argoproj.io/sync-wave: "10"
{{- end }}        
  namespace: {{ $.Values.config_oauth_namespace }}
spec:
  template:
    spec:
      containers:
      - command:
          - /bin/bash
          - -c
          - |
            echo "Checking if Keycloak exists ..."
            for name in $(oc get oauth cluster -o jsonpath='{.spec.identityProviders[*].name}'); do
                if [ "$name" == "keycloak" ]; then
                    echo "found existing keycloak provider, exiting";
                    exit 0
                fi
            done
            echo "Patching OAuth keycloak ..."
            oc get -o yaml oauth/cluster | grep identityProvider
            if [ $? -ne 0 ]; then
                echo "Setting the identityProviders property if missing"
                oc patch oauth/cluster --type=json -p '[{"op":"add", "path":"/spec", "value":{"identityProviders":[]}}]'
            fi
            oc patch oauth/cluster --type=json -p '[{"op":"add", "path":"/spec/identityProviders/-",
              "value":{"openID": {"claims": {"preferredUsername": ["preferred_username"], "name": ["name"], "email": ["email"], "groups": ["groups"]},
              "clientID": {{ $.Values.keycloak.clientid }}, "clientSecret": {"name": {{ $.Values.keycloak.secret }} },
              "ca": {"name": {{ $.Values.keycloak.cm }} }, "issuer": "{{ $.Values.keycloak.issuer }}"},
              "mappingMethod": "claim", "name": "keycloak", "type": "OpenID"}}]'
            exit 0
        image: "quay.io/openshift/origin-cli:latest"
        imagePullPolicy: IfNotPresent
        name: job
      dnsPolicy: ClusterFirst
      restartPolicy: OnFailure
      serviceAccount: config-oauth
      serviceAccountName: config-oauth
      terminationGracePeriodSeconds: 10
{{- end -}}  